devices: 

  sensors:
    - 
      id: 1
      type: usb_camera
      fov: 130
      model: ov5640
      data_mp: 5
      res_width: 2592
      res_height: 1944
      usb_device_path: 
    - 
      id: 1
      model: bme280
      type: air_temp_humidity_barometer
      values:
        temp
        humidity
        pressure
        altitude
    - 
      id: 1
      model: dht210
      type: air_temp_humidity
      values:
        temp
        humidity
        pressure
        altitude
    - 
      model: ds1bb20
      type: soil_temp
      values:
        temp
    - 
      type: soil_mositure
      subtype: capacitive
      model: capacitive
      vendor: 
      values:
        moisture
    - 
      model: tsl2591
      type: light_fullspectrum
      values:
        light_total
        light_ir
        light_visible
        light_fullspectrum
    - 
      model: hcrs04
      type: water_level
      subtype: ultrasonic
      values:
        distance # water level

  actuators:
    - 
      type: light_cwww
      model: 
      voltage: 12
      length_cm: 50
    - 
      type: pump_water
      voltage: 12
    - 
      type: light_rgb
      model: ws2812
      voltage: 5
      leds: 24
      length_cm: 20
    - 
      type: heat_wire
      model: 
      voltage: 12
      length_m: 2
    -
      type: fan
      model: 
      size_mm: 50
      voltage: 12

    
placements:
  zones:
    - 
      id: 1
      devices:
        acuators:
          - 
            type: light_cwww
            id: 1
          - 
            type: water_pump
            id: 1
          - 
            type: fan
            id: 1
          - 
            type: heat_element
            id: 1

        sensors:
          - 
            type: usb_camera
            id: 1
          - 
            type: light
            id: 1
          - 
            type: water_level
            id: 1
          - 
            type: soil_temp
            id: 1
          - 
            type: soil_moisture
            id: 1
          - 
            type: air_temp_humidity_barometer
            id: 1
          - 
            type: air_temp_humidity
            id: 1