protocols:
  default:
    activities:
      - 
        description: grow light schedule
        actions:
          light_cwww:
            repeat:
              d: 1
              h: 0
              m: 0
              s: 0
            action: on, 100, sunramp
            start_time: 
              h: 8
              m: 0
              s: 0
            duration: 
              h: 12
              m: 0
              s: 0
      - 
        description: daily photos
        actions:
          camera:
            repeat:
              d: 0
              h: 12
              m: 0
              s: 0
            action: photo, max_resolution
            start_time: 
              h: 10
              m: 0
              s: 0
      - 
        description: watering triggered 
        actions:
          water_pump:
            trigger: 
              soil_moisture, lt, 80
            action: on
            duration: 30s  
      - 
        description: heating triggered 
        actions:
          heat_wire:
            trigger: 
              soil_temp, lt, 70
            action: on
            duration: 5m  
      - 
        description: fan schedule 
        actions:
          fan:
            repeat: 6h
            action: on, 100
            duration: 3m